# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AthenzUserCert < Formula
  desc "CLI to retrieve Athenz-compatible User Certificate"
  homepage "https://github.com/ctyano/athenz-user-cert"
  version "0.0.321"

  on_macos do
    on_intel do
      url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.321/athenz-user-cert_0.0.321_darwin_amd64.zip"
      sha256 "bb3d05244510917b190ec51f9b0549deb5bf3ed8b2d9a2cfc681299c098431ad"

      def install
        bin.install "athenzusercert"
      end
    end
    on_arm do
      url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.321/athenz-user-cert_0.0.321_darwin_arm64.zip"
      sha256 "acb4f6d0aec3e12b85289d36187821d601e02850daeed0926f91b18ab869d455"

      def install
        bin.install "athenzusercert"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.321/athenz-user-cert_0.0.321_linux_amd64.zip"
        sha256 "9d116f208b692f16b9a6660d047a309efd3ad987ccd329a78e95f37509813917"

        def install
          bin.install "athenzusercert"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.321/athenz-user-cert_0.0.321_linux_arm64.zip"
        sha256 "c99f6e5c9cfcc3d523ecd62ee5a4b68ace36242bbc9e606582f8bce52082f5b2"

        def install
          bin.install "athenzusercert"
        end
      end
    end
  end

  test do
    system "#{bin}/athenzusercert version"
  end
end
