# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AthenzUserCert < Formula
  desc "CLI to retrieve Athenz-compatible User Certificate"
  homepage "https://github.com/athenz-community/athenz-user-cert"
  version "0.0.8"

  on_macos do
    on_intel do
      url "https://github.com/athenz-community/athenz-user-cert/releases/download/v0.0.8/athenz-user-cert_0.0.8_darwin_amd64.zip"
      sha256 "2f08d24eab8d96137f4393e79bae0cbd5bf99574a2ee66d3a9890795d8ba9738"

      def install
        bin.install "athenzusercert"
      end
    end
    on_arm do
      url "https://github.com/athenz-community/athenz-user-cert/releases/download/v0.0.8/athenz-user-cert_0.0.8_darwin_arm64.zip"
      sha256 "eee1be4ced61bfbdd5518889fdeb3b4b9cd20987d7f702c07bdf1372187125f8"

      def install
        bin.install "athenzusercert"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/athenz-community/athenz-user-cert/releases/download/v0.0.8/athenz-user-cert_0.0.8_linux_amd64.zip"
        sha256 "78d3cce5ad6d68a5be29049a5017aa66dea92eb0b22b8a2465c6fadd6ac20025"

        def install
          bin.install "athenzusercert"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/athenz-community/athenz-user-cert/releases/download/v0.0.8/athenz-user-cert_0.0.8_linux_arm64.zip"
        sha256 "e3d9d8d89a49dba0518f46106eb3d295ee2ad3e0214576cd185e51623ef10e24"

        def install
          bin.install "athenzusercert"
        end
      end
    end
  end

  test do
    system "#{bin}/athenzusercert version"
  end
end
