# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AthenzUserCert < Formula
  desc "CLI to retrieve Athenz-compatible User Certificate"
  homepage "https://github.com/athenz-community/athenz-user-cert"
  version "0.0.7"

  on_macos do
    on_intel do
      url "https://github.com/athenz-community/athenz-user-cert/releases/download/v0.0.7/athenz-user-cert_0.0.7_darwin_amd64.zip"
      sha256 "8df510eea11732a1e29a95ff6ff928105ae13c15b84fa16eb1946fd81dd23383"

      def install
        bin.install "athenzusercert"
      end
    end
    on_arm do
      url "https://github.com/athenz-community/athenz-user-cert/releases/download/v0.0.7/athenz-user-cert_0.0.7_darwin_arm64.zip"
      sha256 "8ef40a0e136509adb13e12b68f9934d1d8f01906c00102ead0f783bcc053cde3"

      def install
        bin.install "athenzusercert"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/athenz-community/athenz-user-cert/releases/download/v0.0.7/athenz-user-cert_0.0.7_linux_amd64.zip"
        sha256 "a7a2514b5c4a89a019c6bbb6ed17b2f127d20c7126567e20f50a629d19c54e58"

        def install
          bin.install "athenzusercert"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/athenz-community/athenz-user-cert/releases/download/v0.0.7/athenz-user-cert_0.0.7_linux_arm64.zip"
        sha256 "b5f9e323079d94194466891e5264fe263c16aa2f3ad159149aef4cea5f6c5fe0"

        def install
          bin.install "athenzusercert"
        end
      end
    end
  end

  test do
    system "#{bin}/athenzusercert version"
  end
end
